name: CI SonarQube_code
on:
  push:
    branches:
      -master

jobs:
  analyze:
    name: SonarQube Scan 
    runs-on: windows-latest
    timeout-minutes: 11

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Nécessaire pour une analyse complète

    - uses: SonarSource/sonarqube-scan-action@v5

    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: https://9f03-41-223-51-170.ngrok-free.app
      
          
