name: SonarQube Analysis
on:
  push:
    branches: [ master ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: >
            -Dsonar.host.url=https://your-sonarqube-instance.com  # URL COMPLÈTE avec https://
            -Dsonar.projectKey=1Serahserah_TestAp_37920ed7-4f6e-480c-98a3-48cb946d55b6
            -Dsonar.projectName=TestAp
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.verbose=true
