name: Build and SonarQube Analysis

on:
  push:
    branches:
      - master

jobs:
  sonarqube-analysis:
    name: Build and analyze
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Nécessaire pour une analyse précise

      # Installation des dépendances (ajoutez votre étape de build si nécessaire)
      - name: Set up JDK
        uses: actions/setup-python@v3.10
        with:
          java-version: '17'
          distribution: 'temurin'

      # Analyse SonarQube
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Nécessaire pour les commentaires PR
        with:
          args: >
            -Dsonar.projectKey=1Serahserah_TestAp_37920ed7-4f6e-480c-98a3-48cb946d55b6
            -Dsonar.projectName=TestAp
            -Dsonar.host.url=https://53fe-41-223-51-170.ngrok-free.app
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.java.binaries=.
            -Dsonar.sourceEncoding=UTF-8

      # Vérification de la Quality Gate (optionnel mais recommandé)
      - name: SonarQube Quality Gate Check
        uses: SonarSource/sonarqube-quality-gate-action@v1
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
