name: Build and SonarQube Analysis

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube-analysis:
    name: Build and analyze
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Augmentation du timeout pour les gros projets

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Nécessaire pour une analyse précise

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'  # Activation du cache pour les dépendances

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-cov  # Installation des outils de test

      - name: Run tests with coverage
        run: |
          python -m pytest --cov=./ --cov-report=xml --junitxml=test-results.xml

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=1Serahserah_TestAp_37920ed7-4f6e-480c-98a3-48cb946d55b6
            -Dsonar.projectName=TestAp
            -Dsonar.host.url=https://54cf-197-149-242-67.ngrok-free.app
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.python.version=3.10
            -Dsonar.sources=.
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.python.linting.reportPaths=pylint-report.xml
            -Dsonar.tests=.
            -Dsonar.test.inclusions=**/test_*.py
            -Dsonar.testExecutionReportPaths=test-results.xml
            -Dsonar.verbose=true
            -Dsonar.scm.provider=git
            -Dsonar.useDeprecatedScannerEngine=true  # Important pour SonarQube 25+

      - name: SonarQube Quality Gate Check
        uses: SonarSource/sonarqube-quality-gate-action@v1.6.0
        timeout-minutes: 10
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
