name: SonarQube Analysis
on:
  push:
    branches: [ master, develop ]  # Branches à surveiller
  pull_request:
    types: [ opened, synchronize ]

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Nécessaire pour l'analyse SonarQube

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Auto-généré par GitHub