name: SonarQube Analysis
on: [push]

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        run: |
          sonar-scanner \
            -Dsonar.projectKey=spring-myproject \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Secret correctement nommé
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}  # À définir dans les secrets GitHub