name: Analyse SonarQube Python

on:
  push:
    branches:
      - main  # change en master si ta branche s'appelle master

jobs:
  sonarQube:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # ou une autre version selon ton projet

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true  # si tu as un fichier requirements.txt

      - name: Exécuter l'analyse SonarQube
        uses: SonarSource/sonarqube-scan-action@v1.0.0
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL}}
